---
- hosts:
    localhost

    - name: copy site files & dockerfile
      copy:
        src: ./site
        dest: /tmp
        force: yes

    - name: build the image
      command: docker build ./site -t=centos_nginx_ssh_v32

    - name: run the container
#      command: docker container run -p 8080:80 -p 2022:22 centos_nginx_ssh_v32
      docker_container:
        name: my_site
        image: centos_nginx_ssh_v32
        state: present
        recreate: yes
        ports:
          - "8080:80"
          - "2022:22"      

